name: ci
on:
  pull_request:

env:
  THREADS_WORKER_INIT_TIMEOUT: 15000

jobs:
  # Testing the built files
  Test:
    needs: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [ '18', '20' ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: install dependencies and build
        run: npm install

      - name: Dev test
        env:
          NODE_OPTIONS: --openssl-legacy-provider
        run: npm run test:tooling

      - name: test library
        run: npm run test:library

      - name: test puppeteer
        run: npm run test:puppeteer:basic

      - name: test puppeteer webpack
        run: npm run test:puppeteer:webpack
